services:
  api:
    hostname: ipfs-pin-auth-server
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - ./data:/data
    ports:
      - '8080:80'
      - '127.0.0.1:8088:8088'