services:
  api:
    hostname: ipfs-pin-auth-server
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - ./data:/data
    ports:
      - '8000:80'
      - '127.0.0.1:8088:8088'